POST http://localhost:5000/login

###

POST http://localhost:5000/users/signup
Content-Type: application/json

{
    "username":"faruk",
    "password":"4444",
    "userType":"superAdmin",
    "email":"faruk1@hotmail.com"
}

###

POST http://localhost:5000/users/signin
Content-Type: application/json

{
    
    "email":"faruk@hotmail.com",
    "password":"4444"
}